name: proteingenerator
channels:
  - dglteam/label/cu117
  - nvidia
  - pytorch
  - bioconda
  - defaults
  - conda-forge
  - r
dependencies:
  - biopython=1.81
  - decorator=5.1.0
  - dgl=1.0.2.cu117
  - e3nn=0.5.1
  - icecream=2.1.3
  - pynvml=11.0.0
  - python=3.8.16
  - pytorch=2.0.0
  - pytorch-cuda
  - seaborn=0.12.2
